### ISSUE TITLE
Array allocated with `malloc` freed using `fftw_free`

### ISSUE THREAD

**Issue by janden** [ahbarnett/finufft#18]
In `finufft1d1` and `finufft1d2`, the `fwkerhalf` array is allocated using `malloc` but not freed using `free`. Instead, `fftw_free` is used. This works ok most of the time, but with the MATLAB interface, it causes problems if we have a call to FFTW before, as in
```
fft(randn(800, 1));
finufft1d1(1, 1, 1, 1, 1);
```
If FINUFFT is called before the FFTW call, things work ok
```
finufft1d1(1, 1, 1, 1, 1);
fft(randn(800, 1));
finufft1d1(1, 1, 1, 1, 1);
```
It looks like this has to do with how MATLAB hooks into the `malloc` and `free` functions in some way.

**Comment by ahbarnett** [comment]
I fixed this yesterday. - A
