### ISSUE TITLE
`make` followed by `make PREC=SINGLE` fails

### ISSUE THREAD

**Issue by janden** [ahbarnett/finufft#20]
For example, `make matlab` followed by `make matlab PREC=SINGLE` fails. On the other hand, `make lib` followed by `make lib PREC=SINGLE` does not do anything (from what I understand, it leaves the double-precision library in place). I'm guessing this is due to the files already being there, so make does not try to rebuild them for single precision.

Note that `make clean` does not resolve this, since the libraries are not removed for this target.

Should there be different library names/targets for single and double precision (c.f. fftw)?

**Comment by ahbarnett** [comment]
Hi Joakim - yes, this is expected, since we don't have distinct names per precision yet - I thought about this (see todo list). But thanks for spotting the bug in make clean. I will fix.

**Comment by janden** [comment]
Ok cool. Maybe there should be a warning to get users to do a `make clean` before trying the other precisions? I'm guessing the same holds for `OMP=OFF`.
