### ISSUE TITLE
MATLAB interface incompatible with single precision

### ISSUE THREAD

**Issue by janden** [ahbarnett/finufft#21]
Specifically,
```
make matlab PREC=SINGLE
```
fails.

Since mwrap is hardcoded for double precision, should we simply not allow this?

**Comment by ahbarnett** [comment]
yeah, I don't know how to do this (ie get single to communicate w/ matlab through mwrap) I don't want to write MEX by hand. If there's a way to prevent the make process for this choice, please submit pull request.
