### ISSUE TITLE
mwrap not found

### ISSUE THREAD

**Issue by magland** [ahbarnett/finufft#5]
finufft should not require mwrap to be installed. yet when I do

> make matlab

I get the following compile error:

magland@jm3:~/dev/finufft/tmptmp/finufft$ make matlab
(cd matlab;\
mwrap -list -mex finufft -cppcomplex -mb finufft.mw ;\
mwrap -mex finufft -c finufft.cpp -cppcomplex finufft.mw )
/bin/sh: 2: mwrap: not found
/bin/sh: 3: mwrap: not found
makefile:186: recipe for target 'matlab/finufft.cpp' failed
make: *** [matlab/finufft.cpp] Error 127

After I have installed mwrap (apt install mwrap on ubuntu), it works.

**Comment by magland** [comment]
I am still seeing this issue on a fresh install

**Comment by ahbarnett** [comment]
This was amusing - the reason I thought I had fixed it the first time was that mwrap was *not* called on the fresh install I did.  Here's why: with probability 0.5 matlab/finufft.cpp was created by git clone before matlab/finufft.mw, triggering a rebuild of the former target. I now removed it as a target, and made "make mex" force rebuild it.
